SELECT
    ORDERS.*,
    ORDER_ITEM_SUMMARY.GROSS_ITEM_SALES_AMOUNT,
    ORDER_ITEM_SUMMARY.ITEM_DISCOUNT_AMOUNT
FROM
    {{ref('stg_tpch_orders')}} AS ORDERS
JOIN
    {{ref('int_order_items_summary')}} AS ORDER_ITEM_SUMMARY
        ON ORDERS.ORDER_KEY = ORDER_ITEM_SUMMARY.ORDER_KEY
ORDER BY ORDER_DATE