SELECT
    LINE_ITEM.ORDER_ITEM_KEY,
    LINE_ITEM.PART_KEY,
    LINE_ITEM.LINE_NUMBER,
    LINE_ITEM.EXTENDED_PRICE,
    ORDERS.ORDER_KEY,
    ORDERS.CUSTOMER_KEY,
    ORDERS.ORDER_DATE,
    {{ discounted_amount('LINE_ITEM.EXTENDED_PRICE', 'LINE_ITEM.DISCOUNT_PERCENTAGE') }} AS ITEM_DISCOUNT_AMOUNT
FROM
    {{ ref('stg_tpch_orders') }} AS ORDERS
JOIN
    {{ ref('stg_tpch_line_items') }} AS LINE_ITEM
ON ORDERS.ORDER_KEY = LINE_ITEM.ORDER_KEY
ORDER BY ORDERS.ORDER_DATE 